version: '3'
services:
  working-web:
    build: check-page
    networks:
      - inner
  not-working-web:
    image: nginx:1.17.6
    networks:
      - inner
  grab-page-web:
    build: grab-page
    networks:
      - inner
  working-proxy:
    image: mockserver/mockserver:mockserver-5.8.0
    environment:
      LOG_LEVEL: "DEBUG"
      SERVER_PORT: 1080
      PROXY_REMOTE_PORT: 80
      PROXY_REMOTE_HOST: working-web
    depends_on:
      - working-web
    networks:
      inner:
        aliases:
          - foo.com
          - bar.com
  not-working-proxy:
    image: mockserver/mockserver:mockserver-5.8.0
    environment:
      LOG_LEVEL: "DEBUG"
      SERVER_PORT: 1090
      PROXY_REMOTE_PORT: 80
      PROXY_REMOTE_HOST: not-working-web   
    depends_on:
      - not-working-web
    networks:
      inner:
        aliases:
          - foo.net
          - bar.net
  proxies-redis:
    image: redis:5.0.7
    networks:
      - inner
  proxies-stack:
    image: maxsid/proxies-stack
    restart: "no"
    environment:
      SCAN_INTERVAL: 5
      CHECK_ADDRESS: "http://proxies-service.com"
      CHECK_PATTERN: '<form.+?id="get-code">'
      GRAB_ADDRESS: "http://grab-page-web"
      GRAB_PATTERN: '<td>(?P<host>[\w\d\.].*?)</td>(?s:.*?)<td>(?P<port>\d+)(?s:.*?)<td class="hm">(?P<https>yes|no)'
      REDIS_HOST: "proxies-redis:6379"
    networks:
      - inner
    depends_on:
      - proxies-redis
      - working-proxy
      - not-working-proxy
  python-tester:
    build: tester
    restart: "no"
    depends_on:
      - proxies-stack
    networks:
      - inner
networks:
  inner: